
services:
  mongo:
    image: mongo:6
    container_name: mongo-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network  

  backend:
    build: ./Application-Code/backend
    container_name: backend-app
    env_file:
      - ./Application-Code/backend/.env
    ports:
      - "5000:3000"
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - app-network  

  frontend:
    build: ./Application-Code/frontend
    container_name: frontend-app
    env_file:
      - ./Application-Code/frontend/.env
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app-network  # tu peux le réactiver une fois le backend healthy

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
